#server:
#  port: 8093
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
##          lower-case-service-id: true
##      routes:
##      - id: order_route
#        ### 不使用nacos
##        uri: http://localhost:8092
#        ### 使用nacos,lb指的是从nacos中按照名称获取微服务，并遵循负载均衡策略
##        uri: lb://order
##        order: 1
##        predicates:
##        - Path=/**
#    nacos:
#      server-addr: localhost:8848
#  zipkin:
#    base-url: http://localhost:9411/
#    discovery-client-enabled: false
#  sleuth:
#    sampler:
#      probability: 1.0