#server:
#  port: 8092
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        port: 8100
#        dashboard: localhost:8080
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#  application:
#    name: order
#  zipkin:
#    base-url: http://localhost:9411/
#    discovery-client-enabled: false
#  sleuth:
#    sampler:
#      probability: 1.0
#mybatis:
#  mapper-locations: classpath*:*Mapper.xml
#feign:
#  sentinel:
#    enabled: true
#rocketmq:
#  name-server: localhost:9876
#  producer:
#    group: shop-order